### ISSUE TITLE
Problem with Expansion Statistic

### ISSUE THREAD

**Issue by MaximeMichaud** [PlaceholderAPI/Statistics-Expansion#10]
Version : 2.10.3
/papi ecloud download Statistic
Downloaded without any problem(s)
/papi reload
[PlaceholderAPI] Successfully registered expansion: player
[17:46:24 ERROR]: [PlaceholderAPI] Failed to init placeholder expansion from class: com.extendedclip.papi.expansion.mcstatistics.StatisticsExpansion
[17:46:24 ERROR]: [PlaceholderAPI] 'boolean org.bukkit.Material.isItem()'

**Comment by aBooDyy** [comment]
Hello,

What's your spigot version?
If it's 1.12.2 or older, run the following commands
```
/papi ecloud download Statistic 1.7.0
/papi reload
```
Let me know how it goes for you.

**Comment by MaximeMichaud** [comment]
Sorry I didn't precise the server version.
I am in 1.8.8 and the version Statistic 1.7.0 fix my problem.
Thank you !
