### ISSUE TITLE
Statistic Deaths not counting

### ISSUE THREAD

**Issue by x3mp** [PlaceholderAPI/Statistics-Expansion#15]
PlaceholderAPI/PlaceholderAPI#13 # Issue
> What is the issue? Describe it like you would tell a friend.
Very simple to explain, the statistic death counter isn't working. I tried suiciding a few times and even deopped myself and set my rank to the default rank but no change.  

### Expected behaviour
> What should PlaceholderAPI do?
Count the deaths of the player

### Actual behaviour
> What does PlaceholderAPI actually do?
Not count the deaths

### How to reproduce
> What steps did you made, to get this bug?
I have no idea how to reproduce it. I'm running Paper Spigot 1.12.2
Could this be the issue?

**Comment by aBooDyy** [comment]
Hello there,
For v1.12.2, you'll have to download Statistic expansion v1.7.0.
You can download it from [here](https://api.extendedclip.com/expansions/statistic/versions/statistic-170/) and then replace it with the current one you have in `plugins/PlaceholderAPI/expansions` folder after you do that, reload PlaceholderAPI plugin `/papi reload` and it should work fine.

**Comment by x3mp** [comment]
Okay thank you!

**Comment by aBooDyy** [comment]
Happy to help!
If that fixed it, close this issue, please.
