### ISSUE TITLE
Statistic placeholders not work

### ISSUE THREAD

**Issue by Lunatik934** [PlaceholderAPI/Statistics-Expansion#16]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

Statistic placeholders don't work correctly, %statistic_kills_entity_zombie% cause error, %statistic_mob_kills% also are bugged but I don't have error on console

### Logs

https://paste.helpch.at/bavuxeboga.md

**Comment by aBooDyy** [comment]
Hello there,

The entity type is case sensitive and it uses the types from [here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html).
Can you explain "bugged" for the mob kills placeholder, please?

Thanks for reaching out,
aBooDyy

**Comment by Lunatik934** [comment]
Placeholder don't work, look https://puu.sh/FyJCU/91eab48f16.png

**Comment by Lunatik934** [comment]
yes but when I use "zombie" entity, placeholder send 0 kills but I have killed 10,15

**Comment by aBooDyy** [comment]
> Placeholder don't work, look https://puu.sh/FyJCU/91eab48f16.png

Whats your spigot version?

> yes but when I use "zombie" entity, placeholder send 0 kills but I have killed 10,15

Read what I've mentioned please,
> The entity type is case sensitive and it uses the types from [here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html).

**Comment by Lunatik934** [comment]
I run on Paper 1.8.8

**Comment by Lunatik934** [comment]
Yes but it not work... %statistic_kills_entity_zombie% say I have 0 kills but I've killed 10zombie

**Comment by aBooDyy** [comment]
> Yes but it not work... %statistic_kills_entity_zombie% say I have 0 kills but I've killed 10zombie

As I mentioned, its case sensitive. So the placeholder should be `%statistic_kills_entity_ZOMBIE%`

> I run on Paper 1.8.8

So I'd assume that you're using statistic version 1.7.0. Unfortunately, `%statistic_mob_kills%` placeholder doesn't exist in this version, which is why it's not working.

**Comment by Lunatik934** [comment]
%statistic_kills_entity_ZOMBIE% return; https://puu.sh/FyU4k/889ec78173.png

**Comment by aBooDyy** [comment]
Are you using Statistic expansion v1.7.0? You can check with `/papi info statistic`
If you're not, then you should be. More info can be found [here](https://helpch.at/placeholders#statistic).

**Comment by Lunatik934** [comment]
Yes, https://puu.sh/FyXrc/54367cadb2.png

All this placeholders (https://puu.sh/FyXrP/57dcf10512.png) work fine but (https://puu.sh/FyXsi/e506c851ec.png) are break

**Comment by Lunatik934** [comment]
Okay i found ! it is %statistic_kill_entity_ZOMBIE% and not %statistic_kills_entity_ZOMBIE%
