### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by badbojus** [PlaceholderAPI/Statistics-Expansion#2]
every time i load server or type /papi reload. Running Devbuid 1.13. 
(else expansion works it self)

[Pastebin](https://pastebin.com/UFPPKmLa)

**Comment by aBooDyy** [comment]
Can you give us your PlaceholderAPI version and Statistic expansion version?

**Comment by badbojus** [comment]
why ? who is this ? i didn't asked for any help tho.

**Comment by badbojus** [comment]
i see now, on github. Boy, isn't it a bit too late? i created that topic
one year ago...

**Comment by aBooDyy** [comment]
I saw. and sorry about the delay.
Is it still an issue ? i should have asked this before

**Comment by badbojus** [comment]
it's all good now i guess 🙈😂
