### ISSUE TITLE
Bad Time

### ISSUE THREAD

**Issue by XANT3R** [PlaceholderAPI/Statistics-Expansion#20]
I used placeholder "%statistic_time_played%" and unfortunately it charges days incorrectly. He gives me 1 day and 43 hours when he should have already counted the second day.

My Plugins:
Plugins (48): Announcements*, ArmorStandEditor, AuthMe, Citizens, CoreProtect, CraftBook, Cubesurvstats, DeadChest, DiscordSRV, dynmap*, EasyWhitelist*, Essentials, EssentialsChat, EssentialsSpawn, F3Name, FastLogin, HolographicDisplays, IllegalStack, LiquidTanks, LuckPerms, LWC, LWCTrust, MC-AnvilColors*, MLJobs, MyCommand, OpenInv, PlaceholderAPI, PlayerParticles, PreciousStones, ProtocolLib, ServerRestorer, Shopkeepers, SkinsRestorer, SklepMC*, Skript, skript-mirror*, spark, TAB, TitleManager, Trade, TreeAssist, TuSKe*, UltraBar, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard

Paper Version in /ver:

 [19:11:41 INFO]: This server is running Paper version git-Paper-176 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[19:11:41 INFO]: Checking version, please wait...
[19:11:41 INFO]: Previous version: git-Paper-131 (MC: 1.16.1)
[19:11:41 INFO]: You are 2 version(s) behind

ScreenShot:
https://i.imgur.com/HmKtY18.png

**Comment by HexedHero** [comment]
Exact same issue, 1d of playtime but on the stats on ESC its 26d

**Comment by JHarris12345** [comment]
Will this be fixed?

**Comment by iGabyTM** [comment]
@XANT3R @HexedHero @JHarris12345 this build should fix the issue https://ci.extendedclip.com/job/Statistics-Expansion/9/

**Comment by JHarris12345** [comment]
Will that return the stat to what it was or just start counting normally from there? @iGabyTM

**Comment by JHarris12345** [comment]
I dont think it did reset the playtime stat to whats in your offcial MC statistics. Thats annoying, it should show whats in the official statistics as well as fix 60 hour days

**Comment by JHarris12345** [comment]
@iGabyTM
