### ISSUE TITLE
[Bug] %statistic_time_played% incorrect playtime hours when at least 1 day played

### ISSUE THREAD

**Issue by IamMusavaRibica** [PlaceholderAPI/Statistics-Expansion#26]
%statistic_time_played% placeholder shows incorrect hours when at least 1 day played.

Replication:
`/papi parse me %statistic_time_played% | %statistic_time_played:hours%h`

If the playtime is more than 1 day (24 hours) the first one will show days * 24 + hours , while the other one will show only hours
Probably because %statistic_time_played% doesn't subtract the hours when diving by 24 to get the days

Edit for claritifaction This can cauase 1d 28h with %statistic_time_played% while %statistic_time_played:days% will show 1 and %:hours% will show 4, correcly

**Comment by Andre601** [comment]
Duplicate of #20

**Comment by BlitzOffline** [comment]
Also fixed in #21 

You can find the dev build here: https://ci.extendedclip.com/job/Statistics-Expansion/9/
until its pushed to ecloud
