### ISSUE TITLE
Offline player don't work

### ISSUE THREAD

**Issue by SandakiSurGithub** [PlaceholderAPI/Statistics-Expansion#29]
Hello I use PlaceholderAPI on my server in 1.16.5 and when I parse for example that statistic_player_kills on an offline player it returns nothing to me

**Comment by XanderNuytinck** [comment]
The statistics placeholder expansion requires the player to be online.
You can see this in the actual code [here](https://github.com/PlaceholderAPI/Statistics-Expansion/blob/1ccc68a7ccc939815ebf2c571995a9640398db8c/src/main/java/com/extendedclip/papi/expansion/mcstatistics/StatisticsExpansion.java#L73).

Even though Minecraft 1.15 and above supports retrieving statistics from offline users, this expansion hasn't been updated to utilize the new functionality.

**Comment by BlitzOffline** [comment]
Fixed with #28
