### ISSUE TITLE
Latest Statistic Expansion Corrupted

### ISSUE THREAD

**Issue by axemwa** [PlaceholderAPI/Statistics-Expansion#3]
Having issues with latest statistics expansion is it corrupted? I noticed latest expansion version is much smaller in kilobytes and replacing the expansion with an older version fixed the issue, so latest version must be corrupted

https://github.com/PlaceholderAPI/PlaceholderAPI/issues/45

**Comment by axemwa** [comment]
Other expansions are still working fine on 1.12.2

**Comment by iGabyTM** [comment]
Maybe I'm wrong but the latest version is for 1.13 only

**Comment by axemwa** [comment]
If you mean the plugin itself this was in the latest updates section

( 2.9.2 The legacy versions update
    2.9.2
    This update adds support for any relevant minecraft version...)

**Comment by axemwa** [comment]
The statistic placeholder is the only expansion out of 15 that I'm using on 1.12.2 that isn't working, all other expansions are working

**Comment by axemwa** [comment]
I'm just lucky I had a backup of my server and reverted to the previous expansion version, downloading statistics expansion ingame is the only thing causing any issues atm, so I used an older version that wasn't even on the ecloud anymore

**Comment by iGabyTM** [comment]
No, I'm talking about the expansion, Glare have updated it yesterday for 1.13 and I'm not sure if it still work on the previous versions. You can download other versions from https://api.extendedclip.com/all or https://ci.extendedclip.com

**Comment by axemwa** [comment]
It's the only placeholder I noticed that requires it to be minecraft 1.13 probably wasn't updated properly, also none of those links provided a download link for a previous version

**Comment by darbyjack** [comment]
https://api.extendedclip.com/expansions/statistic/versions/

**Comment by axemwa** [comment]
that one is way outdated what happened to all the others?

**Comment by darbyjack** [comment]
Don't know. Just use the previous one, I'll get around to fixing it.

**Comment by axemwa** [comment]
k thanx all other expansions I'm using still work fine in 1.12, the issue it's mainly giving me with latest statistics expansion is when I try to use them in deluxemenus plugin it prevents access to the menu cause it cant find or recognise the placeholder expansion, but previous expansion version it works fine

**Comment by axemwa** [comment]
@darbyjack The fix you applied for Statistic expansion for 1.12 on Oct. 5, 2018, 5:32a.m. didn't seem to fix it :(
Even tried downloading it manually and putting it in the folder still to no avail.
Placeholder statistic expansion bug causes some plugins to not work like deluxemenus for instance

`[02:09:36 WARN]: [DeluxeMenus] Plugin DeluxeMenus v1.10.5 generated an exception while executing task 3027 java.lang.IllegalArgumentException: The supplied Material does not have a corresponding statistic at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.12.2.jar:git-Paper-1574] at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.getStatistic(CraftPlayer.java:787) ~[patched_1.12.2.jar:git-Paper-1574] at com.extendedclip.papi.expansion.mcstatistics.StatisticsExpansion.onPlaceholderRequest(StatisticsExpansion.java:86) ~[?:?] at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?] at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?] at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?] at com.extendedclip.deluxemenus.menu.MenuItem.getItemStack(MenuItem.java:360) ~[?:?] at com.extendedclip.deluxemenus.menu.Menu$2.run(Menu.java:232) ~[?:?] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1574] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1574] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1574] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]`

**Comment by axemwa** [comment]
Here's a copy of an older 1.12 compatible statistic expansion for reference, this older version doesn't seem to be on the ecloud versions section anymore for some reason, I had it still from an old world backup https://www.dropbox.com/s/a37a1cfsge3zjcn/Expansion-Statistic.jar?dl=1

**Comment by axemwa** [comment]
It's weird though I can still parse the statistic placeholders to players but for some reason deluxemenus can't recognise it anymore after a certain statistic expansion update and as a result is the WARN message you see above in deluxemenus

**Comment by darbyjack** [comment]
It is not updated for 1.13 materials yet. That fix I implemented for 1.12 was for the playtimes.

**Comment by axemwa** [comment]
Ah, all good I'm still using the old statistic expansion version for now
