### ISSUE TITLE
Statistic placeholders not work 

### ISSUE THREAD

**Issue by BranTheOtter** [PlaceholderAPI/Statistics-Expansion#30]
Currently having a issue with statistic expansion. https://i.gyazo.com/7b6c15251d122f5674e7a40831ddef7c.png

You can see on the image deaths and mob kills are fine but suddenly recently the numbers stopped going up.

%statistic_mob_kills%
%statistic_deaths%

These are the placeholders im using

**Comment by BlitzOffline** [comment]
This is a problem with your server software. I've seen that on purpur you can disable the tracking of those statistics. Please go ask your server software provider (paper, airplane, spigot, purpur, etc.)

Thank You
