### ISSUE TITLE
Unknown statistic is sending people to invalid link when on latest spigot version

### ISSUE THREAD

**Issue by BlitzOffline** [PlaceholderAPI/Statistics-Expansion#31]
When a player is on 1.17.1 for example (while 1.17.1 is the latest version), and they use an invalid statistic, they are sent an invalid link (https://helpch.at/docs/1.17.1/org/bukkit/Stastistics.html)

That is because the helpchat docs does not have the latest version of the javadocs. So maybe send them to the spigot link instead?: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Statistic.html

**Comment by iGabyTM** [comment]
What if we use https://docs.docdex.helpch.at/ instead? The reason why I didn't made it return the spigot javadoc link is because different versions have different statistics @BlitzOffline

**Comment by BlitzOffline** [comment]
> What if we use [docs.docdex.helpch.at](https://docs.docdex.helpch.at/) instead? The reason why I didn't made it return the spigot javadoc link is because different versions have different statistics @BlitzOffline

I know why you haven't but I am thinking that somehow, make it so that it returns the spigot link when you're on the latest version. Idk how it would detect that, but it's what I actually meant in my comment.

EDIT: Might be possible if you use Matt's VersionHelper that's used in triumph-gui.

**Comment by iGabyTM** [comment]
I see. I will do that.

**Comment by iGabyTM** [comment]
![image](https://user-images.githubusercontent.com/32105478/193429713-f07f7f8a-6c55-435a-b204-e7956dc241c4.png)
