### ISSUE TITLE
Statistic placeholders return empty String

### ISSUE THREAD

**Issue by Andre601** [PlaceholderAPI/Statistics-Expansion#32]
2 separate issues have been made on my Math Expansion repository, reporting the expansion to not parse sn exression properly.

Looking at the reported issue, I can see one single source, which is the use of the Statistic expansion in both cases.

The issue seems to be the fact that the expansion returns an empty String rather than a default value like 0 or -1, which in return breaks the math expression.

A fix for this would be highly apreciated.

Related issues:
- #1
- https://github.com/Andre601/Math-Expansion/issues/6
- https://github.com/Andre601/Math-Expansion/issues/8

**Comment by iGabyTM** [comment]
Seems like the issue was fixed 
![image](https://user-images.githubusercontent.com/32105478/193428795-fba0e428-1850-4b44-95c6-b37c2ab912dc.png)
