### ISSUE TITLE
PAPI does not want to process statistic expansions' KILL_ENTITY names which contain "_" (for some)

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [PlaceholderAPI/Statistics-Expansion#42]
When we try to parse placeholder %statistic_kill_entity:ender_dragon% where "ender_dragon" can also be "wither_skeleton" or "iron_golem" or anything that contains "_", this error happens:
https://mclo.gs/o3P7bBh

/papi dump Output
https://paste.helpch.at/oxavutaraf

Just to mention as I tested, `cave_spider` and `mushroom_cow` works.

**Comment by iGabyTM** [comment]
It tells you the reason why it fails, there is no statistic for dragons and the other entities.
