### ISSUE TITLE
1.9.2 not work 1.8.8 server.

### ISSUE THREAD

**Issue by successed** [PlaceholderAPI/Statistics-Expansion#8]
can you add 1.8.8 support please.
i now use 1.7.0 and i need %statistic_player_kills% placeholder . 
this placeholder "%statistic_player_kills%" not work in 1.7.0

**Comment by aBooDyy** [comment]
Statistic v1.9.2 doesn't work in MC v.12.2 or older, you'll have to use v1.7.0
```
/papi ecloud download Statistic 1.7.0
/papi reload
```
